### ISSUE TITLE
Table Entries Sort in SelectedTableBuilder

### ISSUE THREAD

**Issue by qooco** [anomalylabs/multiple-field_type#25]
What is that? How it should work. Values not sorted after adding new one. Because sort is not enabled.
```
if (!$this->getFieldType()) {**
            $entries = $entries->sort(
                function ($a, $b) {
                    return array_search($a->id, $this->getSelected()) - array_search($b->id, $this->getSelected());
                }
            );
        }
```
setTableEntries method

**Comment by RyanThompson** [comment]
Hmm sorry I don't quite understand. Also this is in the wrong repo. Please see contribution docs and put issues here: https://github.com/pyrocms/pyrocms/issues
